[package]
name = "aether-desk"
version = "0.1.0"
edition = "2021"
description = "A lightweight, cross-platform wallpaper engine"
authors = ["Your Name <your.email@example.com>"]
license = "MIT"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = ["shell-open", "tray-icon", "system-tray", "notification", "window-all"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
thiserror = "1.0"
log = "0.4"
env_logger = "0.10"
dirs = "5.0"
image = "0.24"
ffmpeg-next = "6.0"
winit = "0.28"
egui = "0.22"
egui-wgpu = "0.22"
wgpu = "0.16"
poll-promise = "0.3"
eframe = "0.22"
rfd = "0.11"
notify = "5.1"
chrono = "0.4"
rand = "0.8"
reqwest = { version = "0.11", features = ["json"] }
futures = "0.3"
async-trait = "0.1"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s" 