[package]
name = "aether-desk"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A modern wallpaper engine for Windows and Linux"

[dependencies]
# Core dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.10"
thiserror = "1.0"
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }

# UI dependencies
eframe = "0.22.0"
egui = "0.22.0"
rfd = "0.11.0"

# Platform-specific dependencies
#[cfg(target_os = "windows")]
winapi = { version = "0.3", features = ["winuser"] }

[build-dependencies]
cc = "1.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
opt-level = 0
debug = true 